// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"database/sql"
	"time"
)

type Recurring struct {
	ID           int64
	UserID       int64
	AmountPence  int64
	Description  sql.NullString
	Frequency    string
	IntervalN    int64
	FirstDueDate time.Time
	NextDueDate  time.Time
	EndDate      sql.NullTime
	Active       bool
	CreatedAt    sql.NullTime
}

type RecurringTag struct {
	RecurringID int64
	TagID       int64
}

type Setting struct {
	Key   string
	Value string
}

type Tag struct {
	ID   int64
	Name string
}

type Transaction struct {
	ID              int64
	UserID          int64
	AmountPence     int64
	TDate           time.Time
	Note            sql.NullString
	CreatedAt       sql.NullTime
	SourceRecurring sql.NullInt64
	DeletedAt       sql.NullTime
}

type TransactionTag struct {
	TransactionID int64
	TagID         int64
}

type User struct {
	ID        int64
	Email     string
	PwHash    string
	CreatedAt sql.NullTime
}
